spring:
  jackson:
    parser:
      allow-unquoted-field-names: true
  data:
    mongodb:
      authentication-database: admin
      database: documents
      host: localhost
      port: 27017
      username: document-service
      password: b5699d56d531870962053f5e36108ebc37048fb51df332ac2522921a961693a5
  
  pdf-kafka-broker-1:
    image: confluentinc/cp-kafka:7.3.2
    hostname: pdf-kafka-broker-1
    container_name: pdf-kafka-broker-1
    ports:
      - "19092:19092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://pdf-kafka-broker-1:9092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:19092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_BROKER_ID: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
    depends_on:
      - zookeeper
  pdf-kafka-broker-2:
    image: confluentinc/cp-kafka:7.3.2
    hostname: pdf-kafka-broker-2
    container_name: pdf-kafka-broker-2
    ports:
      - "19093:19093"
      - "29093:29093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://pdf-kafka-broker-2:9093,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:19093,DOCKER://host.docker.internal:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_BROKER_ID: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
    depends_on:
      - zookeeper
  pdf-kafka-broker-3:
    image: confluentinc/cp-kafka:7.3.2
    hostname: pdf-kafka-broker-3
    container_name: pdf-kafka-broker-3
    ports:
      - "19094:19094"
      - "29094:29094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://pdf-kafka-broker-3:9094,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:19094,DOCKER://host.docker.internal:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_BROKER_ID: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
    depends_on:
      - zookeeper
rest-template:
  timeout: 300000
  pool-size: 10
