spring:
  jackson:
    parser:
      allow-unquoted-field-names: true
  data:
    mongodb:
      authentication-database: admin
      database: documents
      host: localhost
      port: 27017
      username: document-service
      password: pdfdocument
      #uri: mongodb+srv://pdf_document:pdfdocument@document-service.ux4nj27.mongodb.net/?retryWrites=true&w=majority&appName=document-service
rest-template:
  timeout: 300000
  pool-size: 10
