spring:
  jackson:
    parser:
      allow-unquoted-field-names: true
  data:
    mongodb:
      authentication-database: admin
      database: documents
      host: localhost
      port: 27017
      username: document-service
      password: "{cipher}b5699d56d531870962053f5e36108ebc37048fb51df332ac2522921a961693a5"
  kafka:
    topic: download-document-event
    template:
      default-topic: download-document-event
    producer:
      bootstrap-servers: localhost:19092, localhost:19093, localhost:19094
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.apache.kafka.common.serialization.ByteArraySerializer"
      properties:
        retries: 10
    admin:
      properties:
        bootstrap.servers: localhost:19092, localhost:19093, localhost:19094
        retries: 10
        retry.backoff.ms: 100000
rest-template:
  timeout: 300000
  pool-size: 10
