spring:
  jackson:
    parser:
      allow-unquoted-field-names: true
  data:
    mongodb:
      authentication-database: admin
      database: documents
      host: localhost
      port: 27017
      username: document-service
      password: pdfdocument
rest-template:
  timeout: 300000
  pool-size: 10
